# Generated by Django 4.1.5 on 2023-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forummessage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
