# Generated by Django 4.1.5 on 2023-03-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forummessage_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forummessage',
            name='avatar',
        ),
    ]
