# Generated by Django 4.1 on 2022-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profiles',
            name='head',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='city',
            field=models.CharField(default='Minsk', max_length=15),
        ),
    ]
